window.quotes = [
  "Små steg hver dag gir store endringer.",
  "Det er lov å starte på nytt i dag.",
  "Fremgang er bedre enn perfeksjon.",
  "Gjør litt, ikke alt.",
  "I dag er også en mulighet.",
  "Handling slår planlegging.",
  "Rolig tempo er fortsatt tempo.",
  "Det du gjør jevnlig betyr mest.",
  "Start der du er.",
  "Én ting av gangen er nok.",

  "Ikke vent på motivasjon – skap bevegelse.",
  "Det enkle er ofte det riktige.",
  "Du trenger ikke være ferdig, bare i gang.",
  "Dagens innsats teller.",
  "Pauser er også fremgang.",
  "Stabilitet slår intensitet.",
  "Små forbedringer varer.",
  "Det er greit å være underveis.",
  "Ikke sammenlign bakscener med andres fasader.",
  "Det du øver på, blir du bedre på.",

  "Tid brukt riktig er aldri bortkastet.",
  "Alt må ikke skje i dag.",
  "Noen dager handler bare om å møte opp.",
  "Det er styrke i ro.",
  "En beslutning kan endre mye.",
  "Det er lov å ta det sakte.",
  "Resultater kommer av vaner.",
  "Det er nok å gjøre sitt beste.",
  "Små valg former store dager.",
  "Det viktigste er ofte usynlig.",

  "Du trenger ikke ha alle svar.",
  "Stø kurs slår raske rykk.",
  "I dag er en ny side.",
  "Fokus gir retning.",
  "Alt begynner med ett steg.",
  "Tålmodighet bygger mer enn hastverk.",
  "Det er fremgang i å fortsette.",
  "Du vokser også på rolige dager.",
  "En enkel plan er bedre enn ingen.",
  "Det er greit å justere underveis.",

  "Gjør det viktigste først.",
  "Dagen trenger ikke være perfekt.",
  "Små seire teller.",
  "Det er ok å be om hjelp.",
  "Det du gjør ofte, blir en del av deg.",
  "Konsekvens er kraft.",
  "Alt har sin tid.",
  "Stabil innsats gir trygghet.",
  "Du er mer enn én dag.",
  "Det er lov å velge på nytt.",

  "Ro gir klarhet.",
  "En god dag starter med ett valg.",
  "Fremgang kan være stille.",
  "Det er styrke i å fullføre.",
  "En pause kan gi ny retning.",
  "Det enkle holder ofte lengst.",
  "Du trenger ikke gjøre alt alene.",
  "Det er nok å gjøre litt bedre.",
  "Vaner former hverdagen.",
  "I dag er også viktig.",

  "Ikke undervurder små bidrag.",
  "Ting tar tid, og det er greit.",
  "En beslutning av gangen.",
  "Rolige dager bygger grunnmur.",
  "Du lærer også når det er krevende.",
  "Det er lov å feile og fortsette.",
  "Retning er viktigere enn fart.",
  "Dagens innsats har verdi.",
  "Fremgang er sjelden rett linje.",
  "Alt trenger ikke løses nå.",

  "Små justeringer gir stor effekt.",
  "Du kan endre kurs.",
  "Det er styrke i å være konsekvent.",
  "I dag er en mulighet til.",
  "Gjør det du kan, der du er.",
  "Pauser gir perspektiv.",
  "Det er greit å gjøre ting enkelt.",
  "Det viktigste er å fortsette.",
  "Tålmodighet er aktiv innsats.",
  "Små handlinger skaper rytme.",

  "Det er nok å være til stede.",
  "Alt trenger ikke være optimalt.",
  "Fokus på det som er innen rekkevidde.",
  "Det er verdi i jevn innsats.",
  "Du kan ta ett steg nå.",
  "Små valg gjentas blir vaner.",
  "Det er lov å bruke tid.",
  "Fremgang føles ikke alltid stor.",
  "En rolig dag kan være produktiv.",
  "Alt starter med oppmøte.",

  "Du bygger mer enn du tror.",
  "Det er rom for forbedring.",
  "I dag er ikke for sent.",
  "Små seire gir motivasjon.",
  "Det er styrke i struktur.",
  "Det er greit å gjøre det enkelt.",
  "Jevn innsats slår skippertak.",
  "Du er på vei.",
  "Det er nok å gjøre noe.",
  "Ting faller på plass over tid.",

  "Ikke stress frem klarhet.",
  "Det er fremgang i å prøve.",
  "Dagens valg former morgendagen.",
  "Alt trenger ikke være ferdig.",
  "Det er lov å være realistisk.",
  "Små rutiner gir frihet.",
  "Du kan ta pauser uten å gi opp.",
  "Det er nok å være konsekvent.",
  "Fremgang er ofte usynlig først.",
  "Du bygger tillit med handling.",

  "Rolig innsats varer lengst.",
  "Det er rom for justering.",
  "Du kan velge fokus.",
  "Alt må ikke skje samtidig.",
  "Små vaner gir stor effekt.",
  "Det er ok å forenkle.",
  "Du trenger ikke mer motivasjon.",
  "Handling skaper klarhet.",
  "En dag av gangen er nok.",
  "Du er allerede i gang.",

  "Det er styrke i å holde det enkelt.",
  "Fremgang krever ikke hastverk.",
  "Dagens innsats betyr noe.",
  "Du kan ta ett valg nå.",
  "Små skritt er ekte skritt.",
  "Det er lov å justere tempo.",
  "Du gjør mer enn du tror.",
  "Alt begynner med vilje.",
  "Rolige rutiner gir stabilitet.",
  "Det er ok å starte smått.",

  "Ikke vent på perfekte forhold.",
  "Du kan bygge steg for steg.",
  "Fremgang er summen av små valg.",
  "I dag er en del av helheten.",
  "Det er greit å prioritere.",
  "Du trenger ikke gjøre alt.",
  "Stødig innsats gir trygghet.",
  "Det er lov å forenkle planer.",
  "Du beveger deg fremover.",
  "Små steg teller også i dag.",

  "Det viktigste er å fortsette.",
  "Alt trenger ikke være klart.",
  "Du kan ta ansvar i ditt tempo.",
  "Fremgang er også vedlikehold.",
  "Det er ok å ta pauser.",
  "Små vaner gir ro.",
  "Du trenger ikke løpe.",
  "Stabilitet gir rom for vekst.",
  "Det er nok å møte opp.",
  "I dag er også en start.",

  "Du kan justere kursen.",
  "Det er styrke i gjentakelse.",
  "Små forbedringer varer.",
  "Alt skjer ikke på én dag.",
  "Du bygger noe over tid.",
  "Det er greit å ta det rolig.",
  "Handling gir retning.",
  "Du er i prosess.",
  "Fremgang kan være stille.",
  "Dagens innsats er nok.",

  "Du trenger ikke presse frem alt.",
  "Små steg gir trygg fremdrift.",
  "Det er rom for utvikling.",
  "Du kan velge én ting.",
  "Alt må ikke være perfekt.",
  "Stødig tempo gir resultater.",
  "Det er greit å være underveis.",
  "Du gjør det du kan.",
  "I dag teller også.",
  "Små valg skaper rytme."
];
